name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: gitea.anderssonfischer.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_WRITE_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: apps/api
          tags: gitea.anderssonfischer.com/kianandersson/api:${{ gitea.sha }}
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.34.1
      - name: Install helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.3
      - name: Prepare keys
        run: |
          mkdir -p keys
          echo "${{ secrets.PUBLIC_KEY }}" > keys/public.pem
          echo "${{ secrets.PRIVATE_KEY }}" > keys/private.pem
      - name: Deploy
        run: |
          helm upgrade --install api charts/api -n api \
            -f values/api/values.yaml \
            --set-file keys.private=./keys/private.pem \
            --set-file keys.public=./keys/public.pem \
            --set registry.username="${{ secrets.REGISTRY_USERNAME }}"
            --set registry.password="${{ secrets.REGISTRY_READ_TOKEN }}"
            --set application.image=gitea.anderssonfischer.com/kianandersson/api:${{ gitea.sha }}

