name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    container: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - run: docker build apps/api -t gitea.anderssonfischer.com/kianandersson/api:latest
