name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: tcp://127.0.0.1:2376
    steps:
      - run: docker build apps/api -t gitea.anderssonfischer.com/kianandersson/api:latest
