name: Deploy

on: [push]

jobs:
  deploy-infra:
    name: Deploy infra release
    runs-on: ubuntu-latest
    container:
      image: gitea.anderssonfischer.com/kianandersson/runner:3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create kubeconfig
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG" > $HOME/.kube/config

      - name: Validate changes
        env:
          SIMPLY_ACCOUNT_NAME: "${{ secrets.SIMPLY_ACCOUNT_NAME }}"
          SIMPLY_API_KEY: "${{ secrets.SIMPLY_API_KEY }}"
        run: |
          helm diff upgrade infra charts/infra -n infra \
            -f values/infra/values.yaml \
            --set simply.accountName="$SIMPLY_ACCOUNT_NAME" \
            --set simply.apiKey="$SIMPLY_API_KEY"

      - name: Deploy changes
        env:
          SIMPLY_ACCOUNT_NAME: "${{ secrets.SIMPLY_ACCOUNT_NAME }}"
          SIMPLY_API_KEY: "${{ secrets.SIMPLY_API_KEY }}"
        run: |
          helm upgrade --install infra charts/infra -n infra \
            -f values/infra/values.yaml \
            --set simply.accountName="$SIMPLY_ACCOUNT_NAME" \
            --set simply.apiKey="$SIMPLY_API_KEY"

  build-api:
    name: Build and publish api image
    runs-on: ubuntu-latest
    container:
      image: gitea.anderssonfischer.com/kianandersson/runner:3
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: gitea.anderssonfischer.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_WRITE_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - id: meta
        name: Set image metadata
        run: echo "image=gitea.anderssonfischer.com/kianandersson/api:${{ gitea.sha }}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: apps/api
          tags: ${{ steps.meta.outputs.image }}

  deploy-api:
    name: Deploy api release
    runs-on: ubuntu-latest
    needs:
      - build-api
    container:
      image: gitea.anderssonfischer.com/kianandersson/runner:3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create kubeconfig
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG" > $HOME/.kube/config

      - name: Prepare keys
        env:
          API_PRIVATE_KEY: "${{ secrets.API_PRIVATE_KEY }}"
          API_PUBLIC_KEY: "${{ secrets.API_PUBLIC_KEY }}"
        run: |
          mkdir -p keys
          echo "$API_PRIVATE_KEY" > keys/private.pem
          echo "$API_PUBLIC_KEY" > keys/public.pem

      - name: Prepare certificates
        run: |
          mkdir -p certs
          kubectl get secret local-root-ca-keypair -n cert-manager -o jsonpath='{.data.tls\.crt}' | base64 --decode > certs/local.crt

      - name: Validate changes
        env:
          REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
          REGISTRY_READ_TOKEN: "${{ secrets.REGISTRY_READ_TOKEN }}"
        run: |
          helm diff upgrade api charts/api -n api \
            -f values/api/values.yaml \
            --set-file keys.private=keys/private.pem \
            --set-file keys.public=keys/public.pem \
            --set-file certificates.local=certs/local.crt \
            --set registry.username="$REGISTRY_USERNAME" \
            --set registry.password="$REGISTRY_READ_TOKEN" \
            --set application.image=${{ needs.build-api.outputs.image }}

      - name: Deploy changes
        env:
          REGISTRY_USERNAME: "${{ secrets.REGISTRY_USERNAME }}"
          REGISTRY_READ_TOKEN: "${{ secrets.REGISTRY_READ_TOKEN }}"
        run: |
          helm upgrade --install api charts/api -n api \
            -f values/api/values.yaml \
            --set-file keys.private=./keys/private.pem \
            --set-file keys.public=./keys/public.pem \
            --set registry.username="$REGISTRY_USERNAME" \
            --set registry.password="$REGISTRY_READ_TOKEN" \
            --set application.image=${{ needs.build-api.outputs.image }}

  deploy-home-assistant:
    name: Deploy home assistant release
    runs-on: ubuntu-latest
    container:
      image: gitea.anderssonfischer.com/kianandersson/runner:3
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create kubeconfig
        env:
          KUBECONFIG: "${{ secrets.KUBECONFIG }}"
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG" > $HOME/.kube/config

      - name: Validate changes
        env:
          MOSQUITTO_USERNAME: "${{ secrets.MOSQUITTO_USERNAME }}"
          MOSQUITTO_PASSWORD: "${{ secrets.MOSQUITTO_PASSWORD }}"
          MOSQUITTO_PASSWORD_HASH: "${{ secrets.MOSQUITTO_PASSWORD_HASH }}"
        run: |
          helm diff upgrade home-assistant charts/home-assistant -n home-assistant \
            --set mosquitto.username="$MOSQUITTO_USERNAME" \
            --set mosquitto.password="$MOSQUITTO_PASSWORD" \
            --set mosquitto.passwordHash="$MOSQUITTO_PASSWORD_HASH"

      - name: Deploy changes
        run: |
          helm upgrade --install home-assistant charts/home-assistant -n home-assistant \
            --set mosquitto.username="$MOSQUITTO_USERNAME" \
            --set mosquitto.password="$MOSQUITTO_PASSWORD" \
            --set mosquitto.passwordHash="$MOSQUITTO_PASSWORD_HASH"
